services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatOfficialAccountServerMessageBundle\Repository\:
    resource: '../../Repository/'

  WechatOfficialAccountServerMessageBundle\Service\:
    resource: '../../Service/'

  WechatOfficialAccountServerMessageBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  WechatOfficialAccountServerMessageBundle\MessageHandler\:
    resource: '../../MessageHandler/'

  Tourze\DoctrineUpsertBundle\Service\UpsertManager: ~
  Tourze\DoctrineUpsertBundle\Service\ProviderManager: ~
  
  Yiisoft\Strings\Inflector: ~

  doctrine-upsert.property-accessor:
    class: Symfony\Component\PropertyAccess\PropertyAccessor
    factory: [ 'Symfony\Component\PropertyAccess\PropertyAccess', 'createPropertyAccessor' ]
